// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package filter

import (
	"embed"
	"fmt"
	"strconv"
	"strings"
	"testing"

	"golang.org/x/net/bpf"
)

const tcpdumpGoldenDirectory = "testdata/tcpdump-4.99.0-libpcap-1.10.0"

// tcpdumpGoldenFS contains raw `tcpdump -ddd` output generated by tcpdump
// 4.99.0 with libpcap 1.10.0. Keeping the reference programs in the test
// binary makes this compatibility check reproducible without tcpdump in CI.
//
//go:embed testdata/tcpdump-4.99.0-libpcap-1.10.0/*.ddd
var tcpdumpGoldenFS embed.FS

func tcpdumpGoldenInstructions(fixture string) ([]bpf.Instruction, error) {
	out, err := tcpdumpGoldenFS.ReadFile(tcpdumpGoldenDirectory + "/" + fixture)
	if err != nil {
		return nil, fmt.Errorf("read tcpdump golden fixture %q: %w", fixture, err)
	}

	lines := strings.Fields(strings.TrimSpace(string(out)))
	if len(lines) == 0 {
		return nil, fmt.Errorf("tcpdump golden fixture %q contains no instructions", fixture)
	}
	want, err := strconv.Atoi(lines[0])
	if err != nil {
		return nil, fmt.Errorf("parse instruction count %q: %w", lines[0], err)
	}
	if len(lines) != 1+want*4 {
		return nil, fmt.Errorf("tcpdump golden fixture %q has %d fields for %d instructions", fixture, len(lines), want)
	}

	raw := make([]bpf.RawInstruction, want)
	for i := range raw {
		base := 1 + i*4
		op, err := strconv.ParseUint(lines[base], 10, 16)
		if err != nil {
			return nil, fmt.Errorf("parse op %q: %w", lines[base], err)
		}
		jt, err := strconv.ParseUint(lines[base+1], 10, 8)
		if err != nil {
			return nil, fmt.Errorf("parse jt %q: %w", lines[base+1], err)
		}
		jf, err := strconv.ParseUint(lines[base+2], 10, 8)
		if err != nil {
			return nil, fmt.Errorf("parse jf %q: %w", lines[base+2], err)
		}
		k, err := strconv.ParseUint(lines[base+3], 10, 32)
		if err != nil {
			return nil, fmt.Errorf("parse k %q: %w", lines[base+3], err)
		}
		raw[i] = bpf.RawInstruction{Op: uint16(op), Jt: uint8(jt), Jf: uint8(jf), K: uint32(k)}
	}

	insns, decoded := bpf.Disassemble(raw)
	if !decoded {
		return nil, fmt.Errorf("tcpdump golden fixture %q has unsupported instructions", fixture)
	}
	return insns, nil
}

func TestTCPDumpGoldenDecisionEquivalence(t *testing.T) {
	packets := behaviorPacketCorpus(t)
	tests := []struct {
		name    string
		expr    string
		link    LinkType
		fixture string
		packets []string
	}{
		{
			name:    "ethernet icmp",
			link:    LinkTypeEthernet,
			fixture: "en10mb_icmp.ddd",
			packets: []string{
				"ip4-icmp", "ip4-tcp-80", "ip4-udp-53", "ip6-icmp6", "arp-request",
			},
			expr: "icmp",
		},
		{
			name:    "ethernet tcp port",
			link:    LinkTypeEthernet,
			fixture: "en10mb_tcp_and_port_80.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-tcp-443", "ip4-udp-53", "ip6-tcp-80", "ip6-tcp-443",
			},
			expr: "tcp and port 80",
		},
		{
			name:    "ethernet udp port",
			link:    LinkTypeEthernet,
			fixture: "en10mb_udp_and_port_53.ddd",
			packets: []string{
				"ip4-udp-53", "ip4-tcp-80", "ip4-icmp", "ip6-udp-53", "ip6-tcp-80",
			},
			expr: "udp and port 53",
		},
		{
			name:    "ethernet arp",
			link:    LinkTypeEthernet,
			fixture: "en10mb_arp.ddd",
			packets: []string{
				"arp-request", "rarp-request", "ip4-tcp-80", "ip6-udp-53",
			},
			expr: "arp",
		},
		{
			name:    "ethernet ip",
			link:    LinkTypeEthernet,
			fixture: "en10mb_ip.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-udp-53", "arp-request",
			},
			expr: "ip",
		},
		{
			name:    "ethernet ip6",
			link:    LinkTypeEthernet,
			fixture: "en10mb_ip6.ddd",
			packets: []string{
				"ip6-udp-53", "ip6-tcp-80", "ip6-icmp6", "ip4-tcp-80", "arp-request",
			},
			expr: "ip6",
		},
		{
			name:    "ethernet",
			link:    LinkTypeEthernet,
			fixture: "en10mb_tcp_and_port_80_or_udp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-tcp-443", "ip4-udp-53", "ip4-icmp",
				"ip4-multicast", "ip6-udp-53", "ip6-tcp-80", "arp-request",
			},
			expr: "tcp and port 80 or udp",
		},
		{
			name:    "ethernet tcp or udp and not icmp",
			link:    LinkTypeEthernet,
			fixture: "en10mb_tcp_or_udp_and_not_icmp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-tcp-80", "ip6-udp-53", "ip6-icmp6",
			},
			expr: "(tcp or udp) and not icmp",
		},
		{
			name:    "ethernet not tcp or udp",
			link:    LinkTypeEthernet,
			fixture: "en10mb_not_tcp_or_udp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-tcp-80", "ip6-udp-53", "ip6-icmp6", "arp-request",
			},
			expr: "not (tcp or udp)",
		},
		{
			name:    "ethernet host and tcp",
			link:    LinkTypeEthernet,
			fixture: "en10mb_host_10_0_0_1_and_tcp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-tcp-443", "ip4-self-udp", "ip4-udp-53", "arp-request",
			},
			expr: "host 10.0.0.1 and tcp",
		},
		{
			name:    "ethernet host and multicast",
			link:    LinkTypeEthernet,
			fixture: "en10mb_host_10_0_0_1_or_ip_multicast.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-multicast", "ip6-udp-53", "arp-request",
			},
			expr: "host 10.0.0.1 or ip multicast",
		},
		{
			name:    "ethernet negation",
			link:    LinkTypeEthernet,
			fixture: "en10mb_not_tcp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-udp-53", "arp-request",
			},
			expr: "not tcp",
		},
		{
			name:    "raw",
			link:    LinkTypeRaw,
			fixture: "raw_tcp_and_port_80_or_udp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-tcp-443", "ip4-udp-53", "ip4-icmp", "ip4-multicast", "ip6-udp-53", "ip6-tcp-80",
			},
			expr: "tcp and port 80 or udp",
		},
		{
			name:    "raw icmp",
			link:    LinkTypeRaw,
			fixture: "raw_icmp.ddd",
			packets: []string{
				"ip4-icmp", "ip4-tcp-80", "ip4-udp-53", "ip6-icmp6",
			},
			expr: "icmp",
		},
		{
			name:    "raw tcp port",
			link:    LinkTypeRaw,
			fixture: "raw_tcp_and_port_80.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-tcp-443", "ip4-udp-53", "ip6-tcp-80", "ip6-tcp-443",
			},
			expr: "tcp and port 80",
		},
		{
			name:    "raw udp port",
			link:    LinkTypeRaw,
			fixture: "raw_udp_and_port_53.ddd",
			packets: []string{
				"ip4-udp-53", "ip4-tcp-80", "ip4-icmp", "ip6-udp-53", "ip6-tcp-80",
			},
			expr: "udp and port 53",
		},
		{
			name:    "raw ip",
			link:    LinkTypeRaw,
			fixture: "raw_ip.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-udp-53",
			},
			expr: "ip",
		},
		{
			name:    "raw ip6",
			link:    LinkTypeRaw,
			fixture: "raw_ip6.ddd",
			packets: []string{
				"ip6-udp-53", "ip6-tcp-80", "ip6-icmp6", "ip4-tcp-80",
			},
			expr: "ip6",
		},
		{
			name:    "raw IPv6",
			link:    LinkTypeRaw,
			fixture: "raw_ip6_and_udp_and_port_53.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-udp-53", "ip6-tcp-80",
			},
			expr: "ip6 and udp and port 53",
		},
		{
			name:    "raw negation",
			link:    LinkTypeRaw,
			fixture: "raw_not_tcp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-tcp-80", "ip6-udp-53",
			},
			expr: "not tcp",
		},
		{
			name:    "raw tcp or udp and not icmp",
			link:    LinkTypeRaw,
			fixture: "raw_tcp_or_udp_and_not_icmp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-tcp-80", "ip6-udp-53", "ip6-icmp6",
			},
			expr: "(tcp or udp) and not icmp",
		},
		{
			name:    "raw not tcp or udp",
			link:    LinkTypeRaw,
			fixture: "raw_not_tcp_or_udp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-udp-53", "ip4-icmp", "ip6-tcp-80", "ip6-udp-53", "ip6-icmp6",
			},
			expr: "not (tcp or udp)",
		},
		{
			name:    "raw host and tcp",
			link:    LinkTypeRaw,
			fixture: "raw_host_10_0_0_1_and_tcp.ddd",
			packets: []string{
				"ip4-tcp-80", "ip4-tcp-443", "ip4-self-udp", "ip4-udp-53",
			},
			expr: "host 10.0.0.1 and tcp",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ours, err := Compile(tt.expr, tt.link)
			if err != nil {
				t.Fatalf("Compile(%q): %v", tt.expr, err)
			}
			reference, err := tcpdumpGoldenInstructions(tt.fixture)
			if err != nil {
				t.Fatal(err)
			}
			ourVM, err := bpf.NewVM(ours)
			if err != nil {
				t.Fatalf("our VM: %v", err)
			}
			referenceVM, err := bpf.NewVM(reference)
			if err != nil {
				t.Fatalf("tcpdump VM: %v", err)
			}

			for _, name := range tt.packets {
				packet := packets[name]
				if tt.link == LinkTypeRaw {
					packet = rawBehaviorPacket(t, packet)
				}
				got, err := ourVM.Run(packet)
				if err != nil {
					t.Fatalf("our VM on %s: %v", name, err)
				}
				want, err := referenceVM.Run(packet)
				if err != nil {
					t.Fatalf("tcpdump VM on %s: %v", name, err)
				}
				if (got != 0) != (want != 0) {
					t.Errorf("%s: ours=%d tcpdump=%d\nours:    %v\ntcpdump: %v", name, got, want, ours, reference)
				}
			}
		})
	}
}
